language: python

python:
  - 3.7

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
      
before_script:
  - cd install_dependencies
  - python install_dependencies.py
  - cd ..
  
script:
  - python run.py && pytest

